[env:esp32dev]
platform = espressif32@^6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    electroniccats/MPU6050@^1.4.1
    h2zero/NimBLE-Arduino@^1.4.2
